package glide.billing

import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream
import org.apache.pdfbox.pdmodel.common.PDRectangle
import org.apache.pdfbox.pdmodel.font.Standard14Fonts
import org.apache.pdfbox.pdmodel.font.PDType1Font
import java.io.File
import java.time.LocalDate
import java.time.format.DateTimeFormatter

object InvoicePdfWriter {
    private const val MARGIN = 50f
    private const val LINE_HEIGHT = 16f
    private val fileDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd")

    private val fontRegular = PDType1Font(Standard14Fonts.FontName.HELVETICA)
    private val fontBold = PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)

    fun write(content: InvoiceContent, billId: String): File {
        val directory = invoiceDirectory()
        directory.mkdirs()
        val file = File(directory, "invoice-${fileDateFormat.format(LocalDate.now())}-${content.invoiceNumber}.pdf")

        PDDocument().use { document ->
            val page = PDPage(PDRectangle.A4)
            document.addPage(page)
            PDPageContentStream(document, page).use { stream ->
                var y = page.mediaBox.upperRightY - MARGIN

                y = drawText(stream, fontBold, 22f, MARGIN, y, "INVOICE")
                y -= LINE_HEIGHT * 2

                y = drawText(stream, fontBold, 12f, MARGIN, y, INVOICE_FROM_NAME)
                y = drawText(stream, fontRegular, 10f, MARGIN, y, "Invoice no. ${content.invoiceNumber}")
                y = drawText(stream, fontRegular, 10f, MARGIN, y, "Issue date: ${content.issuedDateLabel}")
                y = drawText(stream, fontRegular, 10f, MARGIN, y, "Due: ${content.dueDateLabel}")
                y = drawText(stream, fontRegular, 10f, MARGIN, y, "Status: ${content.status.label}")
                y -= LINE_HEIGHT

                y = drawText(stream, fontBold, 11f, MARGIN, y, "Bill to")
                y = drawText(stream, fontRegular, 10f, MARGIN, y, content.billToName)
                if (content.billToEmail.isNotBlank()) {
                    y = drawText(stream, fontRegular, 10f, MARGIN, y, content.billToEmail)
                }
                if (content.billToPhone.isNotBlank()) {
                    y = drawText(stream, fontRegular, 10f, MARGIN, y, content.billToPhone)
                }
                y -= LINE_HEIGHT * 1.5f

                val amountX = page.mediaBox.width - MARGIN - 80f
                val headerY = y
                drawText(stream, fontBold, 10f, MARGIN, headerY, "Description")
                drawText(stream, fontBold, 10f, amountX, headerY, "Amount")
                y = headerY - LINE_HEIGHT * 0.5f
                stream.moveTo(MARGIN, y)
                stream.lineTo(page.mediaBox.width - MARGIN, y)
                stream.stroke()
                y -= LINE_HEIGHT

                var rowY = y
                drawText(stream, fontRegular, 10f, MARGIN, rowY, content.packLineDescription)
                drawText(stream, fontRegular, 10f, amountX, rowY, content.formattedGross)
                y = rowY - LINE_HEIGHT

                content.creditLines.forEach { credit ->
                    rowY = y
                    drawText(stream, fontRegular, 10f, MARGIN, rowY, credit.description)
                    drawText(
                        stream,
                        fontRegular,
                        10f,
                        amountX,
                        rowY,
                        credit.formattedAmount(content.currencyCode),
                    )
                    y = rowY - LINE_HEIGHT
                }

                y -= LINE_HEIGHT

                stream.moveTo(MARGIN, y)
                stream.lineTo(page.mediaBox.width - MARGIN, y)
                stream.stroke()
                y -= LINE_HEIGHT * 1.5f

                val totalY = y
                drawText(stream, fontBold, 11f, amountX - 40f, totalY, "Total due")
                drawText(stream, fontBold, 11f, amountX, totalY, content.formattedTotal)

                drawText(
                    stream,
                    fontRegular,
                    8f,
                    MARGIN,
                    MARGIN + LINE_HEIGHT,
                    "Generated by Glide · Bill $billId",
                )
            }
            document.save(file)
        }
        return file
    }

    private fun invoiceDirectory(): File {
        val documents = File(System.getProperty("user.home"), "Documents")
        return File(documents, "Glide/invoices")
    }

    private fun drawText(
        stream: PDPageContentStream,
        font: PDType1Font,
        fontSize: Float,
        x: Float,
        y: Float,
        text: String,
    ): Float {
        stream.beginText()
        stream.setFont(font, fontSize)
        stream.newLineAtOffset(x, y - fontSize)
        stream.showText(text)
        stream.endText()
        return y - LINE_HEIGHT
    }
}
